name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{runner.os}}-gradle-${{hashFiles('build.gradle')}}
    - name: Gradle Build
      run: ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: build/libs/
